let data = [
  {
    name: "Gaurav Pandey",
    pro: "./Team_Profile_Pic/Gaurav_Sir.jpeg",
    about: "ADMIN (Creator)",
    linkedin: "https://www.linkedin.com/in/gaurav-pandey-00b75126a/",
    git: "https://github.com/GauravPandey123webdeveloper?tab=repositories",
  },

  {
    name: "Keshav Agarwal",
    pro: "./Team_Profile_Pic/Keshav_Agarwal.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/keshav-agarwal1803/",
    git: "https://github.com/Keshav-1803",
  },
  {
    name: "Arihant Singh Rana",
    pro: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Windows_10_Default_Profile_Picture.svg/2048px-Windows_10_Default_Profile_Picture.svg.png",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/arihant-singh-rana-0710641ba/",
    git: "https://github.com/Arihant-Singh-Rana",
  },
  {
    name: "Sharad Singh Kushwaha",
    pro: "./Team_Profile_Pic/Sharad_Singh_Kushwaha.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/sharad0203/",
    git: "https://github.com/absolutely-sharad",
  },
  {
    name: "Saurabh Prakash",
    pro: "./Team_Profile_Pic/Saurabh_Prakash.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/saurabh-prakash-0715992b3/",
    git: "https://github.com/SaurabhSPKY",
  },
  {
    name: "Ashish Dhamane",
    pro: "./Team_Profile_Pic/Ashish.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/ashish-dhamane-7931a3297/",
    git: "https://github.com/ASHISHBVB",
  },
  {
    name: "Prateek Choudhary",
    pro: "./Team_Profile_Pic/Prateek_Choudhary.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/prateek-choudhary-317422292/",
    git: "https://github.com/Prateek-Fst",
  },
  {
    name: "Anupama Choudhary",
    pro: "./Team_Profile_Pic/Anupama_Choudhary.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/anupama-choudhary-4b1a442a2/",
    git: "https://github.com/Annupamaa",
  },
  {
    name: "Vikas Chaudhary",
    pro: "./Team_Profile_Pic/Vikas_Chaudhary.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/vikas-chaudhary-8b6318289/",
    git: "https://github.com/vikas-chaudhary-2802",
  },
  {
    name: "Adnan Khan",
    pro: "./Team_Profile_Pic/Adnan_Khan.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/adnan-khan-901324207/",
    git: "https://github.com/Beingadnan",
  },
  {
    name: "Purnima Baroi",
    pro: "./Team_Profile_Pic/Purnima_Baroi.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/purnima-baroi-0882072aa/",
    git: "https://github.com/purniiiima",
  },
  
  {
    name: "Priyansh Kandwal",
    pro: "./Team_Profile_Pic/Priyansh.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/priyansh-kandwal69",
    git: "https://github.com/priyansh-69",
  },
  {
    name: "Ayush Srivastava",
    pro: "./Team_Profile_Pic/Ayush_Srivastava.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/ayushsrivastava0609/",
    git: "https://github.com/AyushSrivastava0609",
  },
  {

    
    name: "Aryan Lamba",
    pro: "./Team_Profile_Pic/Aryan_Lamba.jpg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/aryan-lamba-1b2769292/",
    git: "https://github.com/lambaaryan011",
  },
  {
    name: "Abhishek Kumar",
    pro: "./Team_Profile_Pic/Abhishek_Kumar.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/abhishekkumar74/",
    git: "https://github.com/abhishekkumar74",
  },
  {
    name: "Avanish Pal",
    pro: "./Team_Profile_Pic/Avanish_Pal.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/avanishpal143/",
    git: "https://github.com/avanishpal143",
  },
  {
    name: "Jayesh Kakhani",
    pro: "./Team_Profile_Pic/Jayesh_Kakhani.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/jayesh-kakhani-3153682a5/",
    git: "https://github.com/Jayesh09871",
  },
  {
    name: "Mani Kant",
    pro: "./Team_Profile_Pic/Mani_Kant.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/mani-kant-0326362a6/",
    git: "https://github.com/Manikant97",
  },
  {
    name: "Govind Rajput",
    pro: "./Team_Profile_Pic/Govind_Rajput.jpeg",
    about: "Front End Developer",
    linkedin:
      "https://www.linkedin.com/in/govind-rajput-9b249a29a/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    git: "https://github.com/govindrajputFST",
  },
  {
    name: "Lokesh Bijarniya",
    pro: "./Team_Profile_Pic/Lokesh_Bijarniya.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/lokesh-bijarniya/",
    git: "https://github.com/Lokesh-Bijarniya",
  },
  {
    name: "Manas Raj",
    pro: "./Team_Profile_Pic/Manas_Raj.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/manas-raj-a34125293/",
    git: "https://github.com/allAboutManas",

  },{
  name: "Nikhil Raghuwanshi",
    pro: "./Team_Profile_Pic/Nikhil_Raghuwanshi.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/nikhilraghuwanshi/",
    git: "https://github.com/Nikhilraghuwanshi04",
  },
  {
    name: "Rushikesh Dhumal",
    pro: "./Team_Profile_Pic/Rushikesh_Dhumal.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/rushikesh-dhumal-613309246/",
    git: "https://github.com/Rishi2911",
  },
  {
    name: "Saurabh Singh",
    pro: "./Team_Profile_Pic/Saurabh.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/saurabh-singh-aa381128b/",
    git: "https://github.com/Saurabhsing21",
  },
  {
    name: "Himanshu Prajapati",
    pro: "./Team_Profile_Pic/Himanshu.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/himanshu-prajapati-48814724a/",
    git: "https://github.com/himanshu1573",
  },
  {
    name: "Avanish Yadav",
    pro: "./Team_Profile_Pic/Avanish_Yadav.jpeg",
    about: "Front End Developer",
    linkedin: "https://www.linkedin.com/in/avanish-yadav-089156292/",
    git: "https://github.com/Avanishyadav8175/",
  }
];
export default data;
